### PR TITLE
feat: Move charts to their respective visualisation goal page

### PR DESCRIPTION
**Pull request by rdNoir**
## Comparison
image

Note: Missing column chart

## Trend Identification
image

Note: Missing all charts

## Correlation
image

Note: Missing all charts

## Distribution
image

Note: Missing histogram

### CODE REVIEW

**Comment by HeLinChooi** [comment]
Hi @rdNoir , i am sorry that I am not sure what this PR is trying to do. Are you trying to merge this branch into main because the trend identification, correlation page is not working as below
image

image

Also, please always mention which group are you in.

**Review by HeLinChooi — CHANGES_REQUESTED** [review]
Also, include the image of successfully displayed charts so that when we review it we can make sure it is the same as what you see.

**Comment by HeLinChooi** [comment]
Ok I think I can read your mind now @rdNoir . You are adding the pages so we could add the charts later on into those pages. I just realised some teams have multiple charts that do not necessarily belong to one category. 

hi @omar-al-hendi I would like to suggest allowing teams to merge their pages into main if they have charts from different categories e.g. #29 . If we notice a team that has all charts belong to a category we may request them to put all of them in a page before merging the branch into main branch e.g. #36

**Comment by HeLinChooi** [comment]
Just to confirm @rdNoir , what are the new charts that you are trying to merge into main branch? And some pages you opened e.g. `Trend Identification` and `Correlation` are just placeholder pages, am I right?

**Comment by rdNoir** [comment]
Hi @HeLinChooi,  I'm from Group 5. There are no new charts, I just moved existing charts into their respective pages based on their visualisation goals (refer Figma). Yes, `Trend Identification` and `Correlation` are placeholder pages.

**Review by sarahatiqah — APPROVED** [review]

**Review by HeLinChooi — APPROVED** [review]
Approved.

**Comment by omar-al-hendi** [comment]
Is it ready to be merged @sarahatiqah ?

**Comment by sarahatiqah** [comment]
> Is it ready to be merged @sarahatiqah ?

Yes

**Comment by omar-al-hendi** [comment]
**Thank you for your contribution @rdNoir @sarahatiqah @kyuuurina, Please rebase the pull request so we can merge it, 
Feel free to check this [video](https://www.youtube.com/watch?v=sWo9rUObrj8&ab_channel=OmarAlhendi) for guidance.**

**Review by sarahatiqah — APPROVED** [review]

**Comment by sarahatiqah** [comment]
> rebase the pull request so we can merge

@rdNoir has rebased the pull request. Please review and try to merge it. Thanks

**Comment by sarahatiqah** [comment]
> Thank you for your contribution @rdNoir @sarahatiqah @kyuuurina, Please rebase the pull request so we can merge it,
> Feel free to check this [video](https://www.youtube.com/watch?v=sWo9rUObrj8&ab_channel=OmarAlhendi) for guidance.

@rdNoir has rebased the pull request. Please review and try to merge it. Thanks

**Pull request merged**
